FROM astrocrpublic.azurecr.io/runtime:3.1-13

RUN pip install --no-cache-dir \
    apache-airflow-providers-amazon \
    apache-airflow-providers-mongo \
    boto3 \ 
    pymongo \
    pillow \
    img2pdf \
    python-pptx